# Generated by Django 5.2.1 on 2025-06-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
