# Generated by Django 5.2.1 on 2025-06-12 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='date',
            field=models.DateField(verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_app.doctor', verbose_name='Doctor'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_app.patient', verbose_name='Patient'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_en',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_kk',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='reason_ru',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status_en',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status_kk',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status_ru',
            field=models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='time',
            field=models.TimeField(verbose_name='Time'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty',
            field=models.CharField(max_length=100, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty_en',
            field=models.CharField(max_length=100, null=True, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty_kk',
            field=models.CharField(max_length=100, null=True, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='doctor',
            name='specialty_ru',
            field=models.CharField(max_length=100, null=True, verbose_name='Specialty'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Birth date'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_en',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_kk',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='phone_ru',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone'),
        ),
    ]
