# Generated by Django 5.1.7 on 2025-04-16 15:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_app', '0003_alter_appointment_date_alter_appointment_doctor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, null=True, verbose_name='Имя доктора')),
                ('image', models.ImageField(upload_to='image', verbose_name='Фото профиля')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_app.doctor')),
            ],
        ),
    ]
