# Generated by Django 5.2 on 2025-05-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('da_app', '0005_alter_appointment_options_alter_doctor_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='image/', verbose_name="Doctor's image"),
        ),
        migrations.DeleteModel(
            name='DoctorAttachment',
        ),
    ]
