# Generated by Django 5.2 on 2025-06-12 19:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('specialty', models.CharField(max_length=100, verbose_name='Specialty')),
                ('specialty_ru', models.CharField(max_length=100, null=True, verbose_name='Specialty')),
                ('specialty_en', models.CharField(max_length=100, null=True, verbose_name='Specialty')),
                ('specialty_kk', models.CharField(max_length=100, null=True, verbose_name='Specialty')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('image', models.ImageField(blank=True, null=True, upload_to='image/', verbose_name="Doctor's image")),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('phone', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('phone_ru', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('phone_en', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
                ('phone_kk', models.CharField(blank=True, max_length=15, null=True, verbose_name='Phone')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('time', models.TimeField(verbose_name='Time')),
                ('reason', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('reason_ru', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('reason_en', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('reason_kk', models.CharField(blank=True, max_length=255, null=True, verbose_name='Reason')),
                ('status', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, verbose_name='Status')),
                ('status_ru', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True, verbose_name='Status')),
                ('status_en', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True, verbose_name='Status')),
                ('status_kk', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Scheduled', max_length=20, null=True, verbose_name='Status')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_app.doctor', verbose_name='Doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='da_app.patient', verbose_name='Patient')),
            ],
        ),
    ]
